package com.example.detectask.domain.usecase

import com.example.detectask.ui.views.DetectionBox

/**
 * Represents the result of a scene analysis process, including descriptive and visual data.
 *
 * This class bundles all relevant outputs of an analysis run, such as the generated summary text,
 * detected objects, raw JSON (if available), optional file export path, and extracted labels.
 *
 * @property summary A textual summary of the scene, typically generated by a language model or rule-based system.
 * @property boxes A list of visual object detections within the scene (e.g. bounding boxes).
 * @property json Optional raw JSON string containing the structured scene description.
 * @property filePath Optional absolute file path where the result was saved (e.g. JSON file).
 * @property labels A list of label strings derived from the detected objects (for display or metadata).
 */
data class SceneAnalysisResult(
    val summary: String,
    val boxes: List<DetectionBox> = emptyList(),
    val json: String? = null,
    val filePath: String? = null,
    val labels: List<String> = emptyList()
)
